# Generated by Django 4.2.3 on 2023-07-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='name',
        ),
    ]
