# Generated by Django 4.2.3 on 2023-07-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_delivery_delivery_date_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='product',
        ),
        migrations.AddField(
            model_name='report',
            name='delivery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.delivery'),
        ),
    ]
